spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deneme
    username: "root"
    password: "12345"
    driver-class-name: com.mysql.cj.jdbc.Driver


mailbox:
  ui:
    address: "https://mailbox.co"